### ISSUE TITLE
Unquoted `entryModule` reference in Webpack 4, development mode only

### ISSUE THREAD

**Issue by jmar777** [videojs/webwackify#3]
When using `videojs-contrib-hls@qa` with `webpack@4` (I'm uncertain about earlier versions), I'm getting a run time error when the webpack mode is `"development"`.

The error is cased by the following dynamically generated source code being sent to the browser:

```javascript
return __webpack_require__(__webpack_require__.s = ./node_modules/videojs-contrib-media-sources/es5/transmuxer-worker.js);
```

Note the unquoted replacement for `entryModule` (relevant loc in the current webwackify implementation are https://github.com/videojs/webwackify/blob/master/index.js#L73 and https://github.com/videojs/webwackify/blob/master/index.js#L202).

I haven't yet figured out why there's a difference here between development and production mode, but... this is what's happening, anyway. :)

**Comment by gkatsev** [comment]
This was just fixed by #2, hopefully, we'll have a patch release soon.

**Comment by jmar777** [comment]
@gkatsev awesome, thanks!

For some reason GitHub is only showing me 1 open issue and 1 closed issue, neither of which are #2, so it had me wondering why this was #3. Great news, nonetheless. 👍

**Comment by gkatsev** [comment]
PRs and issues share numbering, it's only really obvious with projects that don't have many issues and PRs.

**Comment by jmar777** [comment]
Doh, #TIL.

Btw, I just tested with the `0.1.3` release that you just published, and it works! Thanks so much. 👏

**Comment by gkatsev** [comment]
Awesome, thanks for testing @jmar777!
Thanks @mjneil for putting this together :)
